/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.tecmn.santes.proyecto.view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Enumeration;
import javax.swing.AbstractButton;
import javax.swing.ButtonGroup;
import javax.swing.ButtonModel;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import org.tecmn.santes.proyecto.controller.MaterialPrestadoController;
import org.tecmn.santes.proyecto.model.MaterialPrestado;

public class Menu extends javax.swing.JFrame {

    private final MaterialPrestadoController controller;

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        this.controller = new MaterialPrestadoController();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupCantidad = new javax.swing.ButtonGroup();
        lblTitle = new javax.swing.JLabel();
        lblSubtitle = new javax.swing.JLabel();
        lblDescription = new javax.swing.JLabel();
        lblCantidad = new javax.swing.JLabel();
        lblDocente = new javax.swing.JLabel();
        lblMateria = new javax.swing.JLabel();
        lblHorarioMateria = new javax.swing.JLabel();
        lblFechaPrestamo = new javax.swing.JLabel();
        lblFechaDevolucion = new javax.swing.JLabel();
        lblAlumno = new javax.swing.JLabel();
        txtAlumno = new javax.swing.JTextField();
        cmbMateria = new javax.swing.JComboBox<>();
        txtDevolucion = new javax.swing.JTextField();
        sliderHorario = new javax.swing.JSlider();
        txtDocente = new javax.swing.JTextField();
        txtFechaPrestamo = new javax.swing.JTextField();
        progressBar = new javax.swing.JProgressBar();
        rbtnUno = new javax.swing.JRadioButton();
        rbtnDos = new javax.swing.JRadioButton();
        rbtnTres = new javax.swing.JRadioButton();
        lblCategoria = new javax.swing.JLabel();
        cmbCategoria = new javax.swing.JComboBox<>();
        btnSolicitar = new javax.swing.JButton();
        lblCategoria1 = new javax.swing.JLabel();
        cmbCategoria1 = new javax.swing.JComboBox<>();
        lblProducto = new javax.swing.JLabel();
        txtProducto = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuItemTabla = new javax.swing.JMenuItem();
        menuItemSalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuItemAcerca = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(822, 717));
        setName("Vale"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(null);

        lblTitle.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("campus Minatitlan");
        getContentPane().add(lblTitle);
        lblTitle.setBounds(0, 30, 820, 70);

        lblSubtitle.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        lblSubtitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSubtitle.setText("INSTITUTO TECNOLOGICO DE MINATITLAN");
        getContentPane().add(lblSubtitle);
        lblSubtitle.setBounds(0, 0, 820, 70);

        lblDescription.setFont(new java.awt.Font("Dialog", 2, 18)); // NOI18N
        lblDescription.setText("Vale Para Solicitar, intrumentos, material y libros");
        getContentPane().add(lblDescription);
        lblDescription.setBounds(200, 90, 440, 50);

        lblCantidad.setFont(new java.awt.Font("Courier New", 2, 18)); // NOI18N
        lblCantidad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCantidad.setText("Cantidad");
        getContentPane().add(lblCantidad);
        lblCantidad.setBounds(530, 170, 240, 50);

        lblDocente.setFont(new java.awt.Font("Courier New", 2, 18)); // NOI18N
        lblDocente.setText("Docente");
        getContentPane().add(lblDocente);
        lblDocente.setBounds(300, 290, 240, 50);

        lblMateria.setFont(new java.awt.Font("Courier New", 2, 18)); // NOI18N
        lblMateria.setText("Materia");
        getContentPane().add(lblMateria);
        lblMateria.setBounds(540, 290, 240, 50);

        lblHorarioMateria.setFont(new java.awt.Font("Courier New", 2, 18)); // NOI18N
        lblHorarioMateria.setText("Horario de la Materia");
        getContentPane().add(lblHorarioMateria);
        lblHorarioMateria.setBounds(160, 510, 240, 50);

        lblFechaPrestamo.setFont(new java.awt.Font("Courier New", 2, 18)); // NOI18N
        lblFechaPrestamo.setText("Fecha de prestamo");
        getContentPane().add(lblFechaPrestamo);
        lblFechaPrestamo.setBounds(40, 400, 240, 50);

        lblFechaDevolucion.setFont(new java.awt.Font("Courier New", 2, 18)); // NOI18N
        lblFechaDevolucion.setText("Fecha de devolución");
        getContentPane().add(lblFechaDevolucion);
        lblFechaDevolucion.setBounds(300, 400, 240, 50);

        lblAlumno.setFont(new java.awt.Font("Courier New", 2, 18)); // NOI18N
        lblAlumno.setText("Alumno ");
        getContentPane().add(lblAlumno);
        lblAlumno.setBounds(40, 290, 240, 50);
        getContentPane().add(txtAlumno);
        txtAlumno.setBounds(40, 340, 200, 40);

        cmbMateria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "PROGRAMACION VISUAL", "CIRCUITOS ELECTR. I", "DISEÑO DIGITAL", "TEORIA ELECTROMAGNET", "MEDICIONES ELECTRICAS", "INSTRUMENTACION", "PLC" }));
        getContentPane().add(cmbMateria);
        cmbMateria.setBounds(540, 340, 200, 40);
        getContentPane().add(txtDevolucion);
        txtDevolucion.setBounds(300, 450, 200, 40);

        sliderHorario.setMajorTickSpacing(1);
        sliderHorario.setMaximum(23);
        sliderHorario.setPaintLabels(true);
        sliderHorario.setPaintTicks(true);
        sliderHorario.setValue(0);
        sliderHorario.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                sliderHorarioComponentResized(evt);
            }
        });
        getContentPane().add(sliderHorario);
        sliderHorario.setBounds(40, 570, 460, 50);

        txtDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDocenteActionPerformed(evt);
            }
        });
        getContentPane().add(txtDocente);
        txtDocente.setBounds(300, 340, 200, 40);
        getContentPane().add(txtFechaPrestamo);
        txtFechaPrestamo.setBounds(40, 450, 200, 40);
        getContentPane().add(progressBar);
        progressBar.setBounds(0, 630, 820, 70);

        btnGroupCantidad.add(rbtnUno);
        rbtnUno.setText("1");
        getContentPane().add(rbtnUno);
        rbtnUno.setBounds(570, 240, 50, 30);

        btnGroupCantidad.add(rbtnDos);
        rbtnDos.setText("2");
        getContentPane().add(rbtnDos);
        rbtnDos.setBounds(630, 240, 50, 30);

        btnGroupCantidad.add(rbtnTres);
        rbtnTres.setText("3");
        rbtnTres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnTresActionPerformed(evt);
            }
        });
        getContentPane().add(rbtnTres);
        rbtnTres.setBounds(690, 240, 50, 30);

        lblCategoria.setFont(new java.awt.Font("Courier New", 2, 18)); // NOI18N
        lblCategoria.setText("Categoria");
        getContentPane().add(lblCategoria);
        lblCategoria.setBounds(40, 180, 240, 50);

        cmbCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Instrumentos", "Material", "Libros" }));
        cmbCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCategoriaActionPerformed(evt);
            }
        });
        getContentPane().add(cmbCategoria);
        cmbCategoria.setBounds(40, 230, 200, 40);

        btnSolicitar.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnSolicitar.setText("Solicitar");
        btnSolicitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSolicitarActionPerformed(evt);
            }
        });
        getContentPane().add(btnSolicitar);
        btnSolicitar.setBounds(540, 430, 180, 60);

        lblCategoria1.setFont(new java.awt.Font("Courier New", 2, 18)); // NOI18N
        lblCategoria1.setText("Categoria");
        getContentPane().add(lblCategoria1);
        lblCategoria1.setBounds(40, 180, 240, 50);

        cmbCategoria1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Instrumentos", "Material", "Libros" }));
        cmbCategoria1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCategoria1ActionPerformed(evt);
            }
        });
        getContentPane().add(cmbCategoria1);
        cmbCategoria1.setBounds(40, 230, 200, 40);

        lblProducto.setFont(new java.awt.Font("Courier New", 2, 18)); // NOI18N
        lblProducto.setText("Producto a solicitar");
        getContentPane().add(lblProducto);
        lblProducto.setBounds(300, 180, 240, 50);

        txtProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProductoActionPerformed(evt);
            }
        });
        getContentPane().add(txtProducto);
        txtProducto.setBounds(300, 230, 200, 40);

        jMenu1.setText("File");

        menuItemTabla.setText("Tabla");
        menuItemTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemTablaActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemTabla);

        menuItemSalir.setText("Salir");
        menuItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSalirActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemSalir);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ayuda");

        menuItemAcerca.setText("Acerca de");
        menuItemAcerca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAcercaActionPerformed(evt);
            }
        });
        jMenu2.add(menuItemAcerca);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbtnTresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnTresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnTresActionPerformed

    private void txtDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDocenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDocenteActionPerformed

    private void menuItemTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemTablaActionPerformed
        TablaDeDatos tablaFrame = new TablaDeDatos();
        tablaFrame.setVisible(true);
    }//GEN-LAST:event_menuItemTablaActionPerformed

    private void menuItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuItemSalirActionPerformed

    private void btnSolicitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSolicitarActionPerformed
        int hora = sliderHorario.getValue();
        MaterialPrestado miMaterial = new MaterialPrestado(
                txtProducto.getText(),
                txtAlumno.getText(),
                cmbCategoria.getSelectedItem().toString(),
                txtDocente.getText(),
                cmbMateria.getSelectedItem().toString(),
                obtenerCantidadSeleccionada(btnGroupCantidad),
                txtFechaPrestamo.getText(),
                hora + ":00",
                txtDevolucion.getText());
        controller.agregarMaterial(miMaterial);
        Timer timer = new Timer(10, null); // Cada 10 ms
        timer.addActionListener(new ActionListener() {
            int progreso = 0;

            @Override
            public void actionPerformed(ActionEvent e) {
                progreso++;
                progressBar.setValue(progreso);

                if (progreso >= 100) {
                    timer.stop(); // Detener al llegar al 100%
                }
            }
        });
        progressBar.setValue(0); // Reiniciar la barra por si se usa varias veces
        timer.start(); // Iniciar el "llenado"
        JOptionPane.showMessageDialog(null, "Objeto agregado");


    }//GEN-LAST:event_btnSolicitarActionPerformed

    private void menuItemAcercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAcercaActionPerformed
        JOptionPane.showMessageDialog(null, "Software desarrollado para la materia de programacion visual");
    }//GEN-LAST:event_menuItemAcercaActionPerformed

    private void cmbCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCategoriaActionPerformed

    private void cmbCategoria1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCategoria1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCategoria1ActionPerformed

    private void txtProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProductoActionPerformed

    private void sliderHorarioComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_sliderHorarioComponentResized
        // TODO add your handling code here:
    }//GEN-LAST:event_sliderHorarioComponentResized

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGroupCantidad;
    private javax.swing.JButton btnSolicitar;
    private javax.swing.JComboBox<String> cmbCategoria;
    private javax.swing.JComboBox<String> cmbCategoria1;
    private javax.swing.JComboBox<String> cmbMateria;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblAlumno;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblCategoria;
    private javax.swing.JLabel lblCategoria1;
    private javax.swing.JLabel lblDescription;
    private javax.swing.JLabel lblDocente;
    private javax.swing.JLabel lblFechaDevolucion;
    private javax.swing.JLabel lblFechaPrestamo;
    private javax.swing.JLabel lblHorarioMateria;
    private javax.swing.JLabel lblMateria;
    private javax.swing.JLabel lblProducto;
    private javax.swing.JLabel lblSubtitle;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JMenuItem menuItemAcerca;
    private javax.swing.JMenuItem menuItemSalir;
    private javax.swing.JMenuItem menuItemTabla;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JRadioButton rbtnDos;
    private javax.swing.JRadioButton rbtnTres;
    private javax.swing.JRadioButton rbtnUno;
    private javax.swing.JSlider sliderHorario;
    private javax.swing.JTextField txtAlumno;
    private javax.swing.JTextField txtDevolucion;
    private javax.swing.JTextField txtDocente;
    private javax.swing.JTextField txtFechaPrestamo;
    private javax.swing.JTextField txtProducto;
    // End of variables declaration//GEN-END:variables

    public int obtenerCantidadSeleccionada(ButtonGroup grupo) {
        ButtonModel selectedModel = grupo.getSelection();
        if (selectedModel != null) {
            Enumeration<AbstractButton> buttons = grupo.getElements();
            while (buttons.hasMoreElements()) {
                AbstractButton button = buttons.nextElement();
                if (button.getModel() == selectedModel) {
                    return Integer.parseInt(button.getText());
                }
            }
        }
        return -1; // Si no hay nada seleccionado
    }

}
